# Isso aponta diretamente para a pasta onde estão as pastas 'images' e 'labels'
path: D:/Estudos/BCC/PCS/implantdetect/implantdetect-training/data/processed/dataset_yolo_clahe

# Não repita o caminho todo aqui. Apenas onde estão as imagens dentro do path.
train: images/train
val: images/val

# Número de classes
nc: 5

# Mapeamento de nomes (Mantém igual)
names:
  0: Master Easy - Grip Porous RD 3,75 x 8,5mm
  1: SCW 3711
  2: SCW 3713 
  3: SCW 3785
  4: Titamax Ti Cortical (4,1) 3,75 x 11,0mm